name: PR-BUILD
run-name: BUILD PR by @${{ github.actor }}
on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  link-jira-issue:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: k8s-runner
    steps:
      - uses: eskygroup/github-actions/.github/actions/jira-link-insert@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
 
  build-docker-image:
    runs-on: k8s-runner
    timeout-minutes: 15
    env:
      PUSH_REGISTRY: eu.gcr.io
      PULL_REGISTRY: europe-docker.pkg.dev
      API_IMAGE_NAME: esky.payments.authenticator
      IMAGE_REPO: esky-ets-transaction-ci
      IMAGE_TAG_SUFFIX: gh-b${{ github.run_number }}-${{ ( github.event_name != 'workflow_dispatch') && 'spin' || 's-spin' }}
      CI_BUILD: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker pull registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PULL_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_GITHUB_IMAGE_REGISTRY_RW }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "source/Esky.Payments.Authenticator/Dockerfile"
          push: false
          load: true

  run-snyk-scan:
    runs-on: k8s-runner
    timeout-minutes: 15
    env:
      DOTNET_INSTALL_DIR: ./.dotnet
      CI_BUILD: true
    permissions: write-all
    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run Snyk tests
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that following steps will be executed
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --json-file-output=snykreport/snyk.json --severity-threshold=high --sarif-file-output=snykreport/snyk.sarif --file=./Esky.Payments.Authenticator.sln
      
      - name: Parse Snyk report
        run: |
          SNYKERRORS=$(cat ./snykreport/snyk.json | jq '. | map(select(.ok == false)) | length')
          echo "snyk_errors=$SNYKERRORS" >> $GITHUB_ENV
          if [[ $SNYKERRORS == 0 ]]; then
            echo "::notice::snyk found 0 vulnerabilities";            
          else 
            echo "::warning::snyk found $SNYKERRORS vulnerabilities"; 
          fi
                
      - name: Comment Snyk vulnerabilities
        uses: actions/github-script@v7
        with:
          script: |            
            if(process.env.snyk_errors > 0){
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `> [!WARNING] \n> # :dog2: Snyk vulnerabilities report \n> ### [Found ${process.env.snyk_errors} vulnerabilities](https://app.snyk.io/org/esky)`
              })
            }            

      - name: Archive Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snykreport
          retention-days: 7
          